### ISSUE TITLE
[Keyboard Navigation – Howdy – Delete]: Focus is moving to the background elements after selecting “Delete” button.

### ISSUE THREAD

**Issue by v-gasikk** [howdyai/howdy-website#11]
**User Experience:**
Users who rely on keyboards will affect to navigate, if focus is moving background elements after selecting “Delete” button.

**Test Environment:**
OS: Win 10 Version 1809 (OS Build 17763.316)
URL: https://howdy.ai/
Browser: Edge

**Repro Steps:**
Step 1: Open the above URL in edge browser.
Step 2: Open this URL: https://hcl-szz1925.howdy.ai/dashboard in edge.
Step 3: “Dashboard” page gets opened.
Step 4: Navigate to “Scripts” tab and select it.
Step 5: Navigate to “Delete” button and select it.
Step 6: Verify whether focus is moving background elements after selecting “Delete” button.

**Actual Result:**
Focus is moving to the background elements after selecting “Delete” button in “Scripts” tab.

**Expected Result:**
Focus should not move to the background elements after selecting “Delete” button in “Scripts” tab. Focus should move to “Delete” button instead of moving background elements after selecting delete button.

**Note**: Same issue repros on "Script deleted" window.

**MAS Reference Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}](url)

[MAS2.4.3_Howdy_Delete dialog.zip](https://github.com/howdyai/howdy-website/files/2973635/MAS2.4.3_Howdy_Delete.dialog.zip)

**Comment by benbrown** [comment]
OK! The focus now lands on the "DELETE" button in the modal, then the "OK" button in the confirm.

**Comment by v-gasikk** [comment]
Verified and Issue is Not Fixed.
Focus is moving to the out of delete and script delete dialogs.
After selecting "Delete" button, focus is landing on "Delete" then if user press tab key continuously focus is moving out of the dialog. Focus is moving background elements.
User Expected: Focus should move inside dialog only instead of moving background elements.

[MAS2.4.3_Scripts_NotFixed.zip](https://github.com/howdyai/howdy-website/files/3011788/MAS2.4.3_Scripts_NotFixed.zip)

**Comment by benbrown** [comment]
This has been fixed.

**Comment by benbrown** [comment]
The focus will now cycle through the modal buttons.

**Comment by v-gasikk** [comment]
Verified. Issue is Fixed. Hence Closing the bug
