### ISSUE TITLE
[Programmatic access -Howdy-for-pms]: Zooming and scaling are disabled for howdy for pms page.

### ISSUE THREAD

**Issue by v-gasikk** [howdyai/howdy-website#20]
**User Experience**
People, with low vision, will face difficulty as zoom does not follows keyboard focus when a section was created.

**Test Environment**
OS: Win 10 Version 1809 (OS Build 17763.316)
URL: https://hcl-szz1925.howdy.ai/dashboard
Browser: Edge
 
**Repro Steps**
Step 1: Open the URL: https://hcl-szz1925.howdy.ai/dashboard
Step 2: Navigate to "Dashboard" tab and select it.
Step 3: Navigate to "Howdy for Your PM" link and select it.
Step 4: "Howdy for Your PM" page gets opened.
Step 5: open the developer tool bar by using F12 key 
Step 6: Observe the issue 

**Actual Result**
Zooming and scaling are disabled for howdy for pms page.

**Expected Result**
Zooming and scaling must not be disabled for howdy for pms page

**Suggested Fix**
maximum-scale on <meta> tag disables zooming on mobile devices

**Mas Reference**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b69e5ccc-dde2-4406-b550-4deb38648f6d}
![MAS1 4 4_Howdy-K4W](https://user-images.githubusercontent.com/48272005/54474188-deb6be80-4807-11e9-99cd-fda84df2c2d3.png)
![MAS1 4 4_Meta tag](https://user-images.githubusercontent.com/48272005/54474197-fc842380-4807-11e9-9568-ad43fbaaa989.png)

**Comment by benbrown** [comment]
This page and the entire help site has been deprecated and removed from the site.

**Comment by v-gasikk** [comment]
Now this page is not available. Closing this issue based on developer comment.
