### ISSUE TITLE
[Screen reader-Howdyai]: In backward navigation screen reader is reading as here link which is not descriptive.

### ISSUE THREAD

**Issue by v-gasikk** [howdyai/howdy-website#3]
**User Experience:**
Users who depend on screen reader will be affected as in backward navigation screen reader  is not reading the link descriptive so the user will be affected. 
 
**Test Environment:**
OS: Win 10 Version 1809 (OS Build 17763.379)
URL: https://howdy.ai/
Browser: Edge
Screen reader: Narrator
 
**Repro Steps:**
Turn on the narrator 
Step 1: Open the above URL in Edge browser.
Step 2: Navigate to the here link by using backward navigation  using keyboard Shift+tab key.
Step 3: Observe the issue.
 
**Actual Result:**
In backward navigation screen reader is reading as “here” link which is not descriptive.
 
**Expected Result:** 
In backward navigation also screen reader should read as” howdyai makes bots skills and conversational apps here link” 

 

[Usability_Here link.zip](https://github.com/howdyai/howdy-website/files/2971214/Usability_Here.link.zip)

**Comment by benbrown** [comment]
I have added an aria-label and a title tag to this link.  I believe this should resolve the issue!

**Comment by v-gasikk** [comment]
Verified. Issue is Fixed and Closing the bug.
