### ISSUE TITLE
[Keyboard Navigation -Howdyai]: After selecting the Dashboard tab control again press the tab key focus is moving to the Howdy image instead of moving to scripts tab control 

### ISSUE THREAD

**Issue by v-gasikk** [howdyai/howdy-website#8]
**User Experience**
Users who rely on keyboards will get effected to navigate the tab controls if focus is not moving to the expected control when user selecting any control.

**Test Environment**
OS: Win 10 Version 1809 (OS Build 17763.316)
URL: https://howdy.ai/
Browser: Edge
 
**Repro Steps**
Step 1: Open the https://howdy.ai/ url in Edge browser
Step 2: "Howdy Dashboard" page gets opened.
Step 3: Navigate to "Dashboard" tab and select it.
Step 4: "Howdy Dashboard" page gets opened.
Step 5: Press the tab key 
Step 6: Observe the issue.

**Actual Result**
After selecting the Dashboard tab control again press the tab key focus is moving to the Howdy image instead of moving to scripts tab control 
Same issue repro for Scripts tab control also 
 
**Expected Result**
 After selecting the Dashboard tab control again press the tab key focus should moves to the scripts tab control only. 

**Note** After selecting the Pause button again press the tab key focus is moving to the Howdy image instead of Howdy for your team link.
Please refer the attachment: MAS3.2.1_Pause button 

**Mas Reference**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a4bbd37d-ee11-485e-b5c8-0539f0ac94b2}

[MAS3.2.1_Dashboard tab.zip](https://github.com/howdyai/howdy-website/files/2973588/MAS3.2.1_Dashboard.tab.zip)
[MAS3.2.1_Pause button.zip](https://github.com/howdyai/howdy-website/files/2973589/MAS3.2.1_Pause.button.zip)

**Comment by benbrown** [comment]
* The active tab is now automatically focused at page load

From Dashboard, press tab
goes to Scripts tab.


From Scripts, press tab
goes to "create a script" input field.

I believe this is now the correct behavior!

**Comment by v-gasikk** [comment]
Verified. Issue is Fixed. Hence Closing the bug
